openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack Web
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is the documentation for the AquaTrack application.
    You can register, log in, track daily water consumption,
    calculate daily water needs, and view your water intake history.
tags:
  - name: Authentication
    description: Operations related to user authentication.
  - name: User
    description: Operations related to user information.
  - name: Water
    description: Operations related to water consumption tracking.

servers:
  - url: https://back-end-aquatrack.onrender.com
    description: Production server

security:
  - bearerAuth: []

paths:
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/post/login.yaml'
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/post/register.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/post/refresh.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/post/logout.yaml'
  /user:
    get:
      $ref: '../swagger/paths/user/get.yaml'
  /user/update:
    patch:
      $ref: '../swagger/paths/user/patch.yaml'
  /user/avatar:
    post:
      $ref: '../swagger/paths/user/post.yaml'
  /water/day/{date}:
    get:
      $ref: '../swagger/paths/water/{date}/getconsumption.yaml'
  /water/month/{date}:
    get:
      $ref: '../swagger/paths/water/{date}/getmonth.yaml'
  /water/{id}:
    patch:
      $ref: '../swagger/paths/water/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/water/{id}/delete.yaml'
  /water:
    post:
      $ref: '../swagger/paths/water/post.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
